@RestorSimplon_HostAddress = https://localhost:7265


GET {{RestorSimplon_HostAddress}}/categories

###

POST {{RestorSimplon_HostAddress}}/categories
Content-Type: application/json

{
  "Category_Name" : "Diner"
}

###

GET {{RestorSimplon_HostAddress}}/items

###

POST {{RestorSimplon_HostAddress}}/items
Content-Type: application/json

{
  "Name" : "Frite",
  "Price" : 1.70,
  "CategoryId" : 2
}
###

GET {{RestorSimplon_HostAddress}}/items/2/with-category

###

@id=2
GET {{RestorSimplon_HostAddress}}/categories/{{id}}/with-items

###

GET {{RestorSimplon_HostAddress}}/orders

###
